apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB+bdQDzFtW6rOXmno0SyVly9HGeCEdHRka0FK/OBa6Fnw+ZA+ciPJoLZrGN49JJ0gOise2BjqjqpKp1wmh3bQchOm89Isg9GUjjWqMnQbmOS9KZF++HEUr7CwGzYPEf2hMphsk0tscqenkazq+QMEXKQcqgefh7MniDEK4EIjoAWhL6eQNX22snFJuerwVluGqptjEgmDUeovCkD+Zhv3ETn5CxM0v90gNWUulyJOfK/cgCN7PnvyIYsAJ8kN9hQnSSUJVCDlzy0kGXERNdsjCXXhbqrKUHS4LYJQmo4HSbE6jto2ThwJyl1kFTTmKlrkvje+YWMQylBaid1Up2RKLZtY6IkYLjtiJDgU480GEKw5Uz5enrg4GykAXRxOMHudP6r3HGGovTUmKlTAtxx13ubGMQqVd7qvwtR18hF/jl6SZFGSfY0oE283NBJI6GqDBh+ucQWdW+fY98fYeKRLr7X47VrfFatxNg1Ljr3RcKSLiKJX5g4wQA5++bUihdO/3sSVM2yu1u1nFiJYkbqhO9Orq3FN8MF5VMFtJItFjAbebHmvnn2H4Tgy7nQ0JTPnumhUgR5d6pph7dcW9KM03QioulIXR4rx3wTBiPeYe75nqcCuKNeFJcBwMc9uJZfCsiE+7MycLk21GXS/y38m0W/yKSWoGdg8JE0kzXgoiN+hiWbrgdDiKtNodh8+Zr8vt0eJ9a6uwCoVvZsEuXHvIdHcMW4lR/8cP2BfqxV1myHA8Kk+Lh8lX9GQ5+WzvGb7bcSDCQe9ae0WG24LlVUu9s6fNxQMeJNaGOystCiYsnvrmb+CI9b3o69CbRSaQdeFbVN5NUq9QBN284zfkg64YNdaeyQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

