apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCXpc88UEkrb0zsVHTIAELoEcDwqdxODlqjk46ep2+VkqUxKzvEn2nAuN0mthck+Q/VG3oseYKHAgQTpuJ9ATu07W7l/EMFY5L/jNcWH9E4tdm799yAVjPP0w0yTAUhmvDgnQo3qtELMK+O2myDmhNanyMBeQM+IhnkDyW5WqZhQwMLEIfBdU54gYfLK++YNfz1v7aXhyQ6AkSN6RUyuHw0ODtoGEFLR+W65ZuiIJ1vNuqYCKhsZne3Tmb/fOKjn3dsyrnTPKapO22yExiQQiXnLzMc8kfAcIWVaMn+V/2xY2cvFgBLAfhoJIzJoUxDvrmINRAUEofp6zYaKGIfPUySqRzt94TMrt2ZuydoLxNH0rhZI5EuGzijBFs2sKCoxZkCG+ohZlkMbqMGA9M8Ai1FZlPoSEqstB6jl5DoZq2ErKljY/rZBLbaWif1JcMMgfkQ0Hvg4tn38898kjGVtPA2acGO4Rkxyngv8EzVCNe2atdR2g3gpMj1giU/wieC2zSYq4FX0174WqJ4ZHgqdF4Q6yMw8W8sQdHfRmu//COvB4cT2oDuGOtTSzwNxjXh/HcxArE5z15KfOB4rm560WFi3ym3+70gDX3S3EaJqHnMPdkqmQfBZBfWnSKmmnIjbTJDdECKVSH9qP3gNVmnPGJ/hrd7lmF2NwT7iocYh6QcpoSPqj6tw3X9pQJO7iFCz0TwfZklppCC22tCVZv4u3LxYh86iDKZHhWxkXboUIEjgNie5E8CijIAaj9aJvPrBLnaereC0ARHYLtND2EzjeEmTEpscJjgNdQ2J6N5nUe9WYkXmgXwEKMATKUUNwMs89FkgJrzvc596ECVd3p8cK/ujvRpow==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

