apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a-apps-reqs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: team-app-reqs
    repoURL: https://github.com/abhishekamte/platform-over-k8s
    targetRevision: HEAD
  destination:
    server: https://037B0D2D2B2D7238D663AABB64A3372B.yl4.eu-west-3.eks.amazonaws.com
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
